<?php
/**
 * @param array    $attributes The block attributes.
 * @param string   $content    The block default content.
 * @param WP_Block $block      The block instance.
 *
 * @see https://github.com/WordPress/gutenberg/blob/trunk/docs/reference-guides/block-api/block-metadata.md#render
 */
?>
<div
	<?php echo get_block_wrapper_attributes(); ?>
	data-wp-interactive="iapiTabs"
>
	<div class="tab-nav" role="tablist">
		<button
			role="tab"
			class="tab-nav__button"
			data-wp-on--click="actions.selectTab"
			aria-selected="true"
			id="tab-1"
			aria-controls="panel-1"
			tabindex="0"
		>
			ナビ1
		</button>
		<button
			role="tab"
			class="tab-nav__button"
			data-wp-on--click="actions.selectTab"
			aria-selected="false"
			id="tab-2"
			aria-controls="panel-2"
			tabindex="-1"
		>
			ナビ2
		</button>
		<button
			role="tab"
			class="tab-nav__button"
			data-wp-on--click="actions.selectTab"
			aria-selected="false"
			id="tab-3"
			aria-controls="panel-3"
			tabindex="-1"
		>
			ナビ3
		</button>
	</div>
	<div
		id="panel-1"
		role="tabpanel"
		tabindex="0"
		aria-labelledby="tab-1"
		class="tab-panel"
		aria-expanded="true"
		aria-hidden="false"
	>
		パネル1
	</div>
	<div
		id="panel-2"
		role="tabpanel"
		tabindex="0"
		aria-labelledby="tab-2"
		class="tab-panel"
		aria-expanded="false"
		aria-hidden="true"
	>
		パネル2
	</div>
	<div
		id="panel-3"
		role="tabpanel"
		tabindex="0"
		aria-labelledby="tab-3"
		class="tab-panel"
		aria-expanded="false"
		aria-hidden="true"
	>
		パネル3
	</div>
</div>
